//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoHead.proto
namespace protocol
{
    [global::ProtoBuf.ProtoContract(Name=@"ENetworkMessage")]
    public enum ENetworkMessage
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"KEEP_ALIVE_SYNC", Value=0)]
      KEEP_ALIVE_SYNC = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_REQ", Value=1)]
      LOGIN_REQ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RSP", Value=2)]
      LOGIN_RSP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_USERINFO_REQ", Value=3)]
      GET_USERINFO_REQ = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_USERINFO_RSP", Value=4)]
      GET_USERINFO_RSP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_REQ", Value=5)]
      LOGOUT_REQ = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT_RSP", Value=6)]
      LOGOUT_RSP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OFFLINE_SYNC", Value=7)]
      OFFLINE_SYNC = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_QUESTION_INFO_REQ", Value=8)]
      GET_QUESTION_INFO_REQ = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_QUESTION_INFO_RSP", Value=9)]
      GET_QUESTION_INFO_RSP = 9
    }
  
}