//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: QuestionData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuestionItem")]
  public partial class QuestionItem : global::ProtoBuf.IExtensible
  {
    public QuestionItem() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private int _category;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int category
    {
      get { return _category; }
      set { _category = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _step;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"step", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int step
    {
      get { return _step; }
      set { _step = value; }
    }
    private protocol.OptionItem _qA;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"qA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protocol.OptionItem qA
    {
      get { return _qA; }
      set { _qA = value; }
    }
    private protocol.OptionItem _qB = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"qB", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.OptionItem qB
    {
      get { return _qB; }
      set { _qB = value; }
    }
    private protocol.OptionItem _qC = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"qC", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.OptionItem qC
    {
      get { return _qC; }
      set { _qC = value; }
    }
    private protocol.OptionItem _qD = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"qD", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.OptionItem qD
    {
      get { return _qD; }
      set { _qD = value; }
    }
    private string _answer;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"answer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string answer
    {
      get { return _answer; }
      set { _answer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OptionItem")]
  public partial class OptionItem : global::ProtoBuf.IExtensible
  {
    public OptionItem() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private int _isPic;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"isPic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int isPic
    {
      get { return _isPic; }
      set { _isPic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}